version: "3"

vars:
  PKG_PROTO_PATH: proto
  PKG_GEN_PATH: ./gen/go

tasks:
  generateForUserService: 
    aliases: 
      - gen
    desc: "generate"
    cmds: 
      - protoc -I {{.PKG_PROTO_PATH}} {{.PKG_PROTO_PATH}}/userService/userService.proto --go_out={{.PKG_GEN_PATH}} --go_opt=paths=source_relative --go-grpc_out={{.PKG_GEN_PATH}} --go-grpc_opt=paths=source_relative